### ISSUE TITLE
我是windows环境

### ISSUE THREAD

**Issue by sunfengqi** [atnet/go2o#2]
我表创建了，build 也没有错。然后./servser输出
![qq 20150106014905](https://cloud.githubusercontent.com/assets/1744938/5617180/d4d1b136-9546-11e4-84bb-ae352a15ed8c.png)
控制台啥也没有了。我在浏览器输入http://127.0.0.1:1001/显示101: no such partner

我不明白接下来怎么办了，pm_siteconf host怎么填。求楼主赐教

**Comment by sunfengqi** [comment]
求楼主联系方式。跪谢

**Comment by newmin** [comment]
已经补充在README.md中了
https://github.com/newmin/go2o#3add-http-proxy-by-nginx

**Comment by sunfengqi** [comment]
![ssss](https://cloud.githubusercontent.com/assets/1744938/5625461/0fa572d8-95b6-11e4-9b9c-89f7ccc83863.png)
我在输入http://wly.ts.com/时出现的http://member.ts.com/ http://partner.ts.com/都出现正常的页面

**Comment by sunfengqi** [comment]
有没有管理系统带有权限之类的，管理中心怎么注册。

**Comment by atnet** [comment]
不好意思，一直没上来看。建议用最新的代码编译。 系统没有权限管理，管理中心可用
dsp.PartnerService.NewPartner(....)来添加一个新的商户，有一个默认的商户wly
密码:123456  ,管理进入partner.ts.com,商户入口:wly.ts.com
