### ISSUE TITLE
显示类重定义 ？  go version 1.4.2 on  windows

### ISSUE THREAD

**Issue by bzhkl** [atnet/go2o#5]
# go2o/src/app/front/webui/www
src\app\front\webui\www\web_c.go:18: baseC redeclared in this block
        previous declaration at src\app\front\webui\www\base_c.go:22
src\app\front\webui\www\web_c.go:22: (*baseC).GetPartnerId redeclared in this bl
ock
        previous declaration at src\app\front\webui\www\base_c.go:49
src\app\front\webui\www\web_c.go:38: (*baseC).GetPartner redeclared in this bloc
k
        previous declaration at src\app\front\webui\www\base_c.go:52
src\app\front\webui\www\web_c.go:43: (*baseC).GetMember redeclared in this block

        previous declaration at src\app\front\webui\www\base_c.go:62

**Comment by atnet** [comment]
windows上似乎有bug. 不支持匿名组合的方法继承。 go2o 是在mac下开发的,
跟windows有些不同，建议在非windows下使用。

**Comment by bzhkl** [comment]
type Base struct { 
    ... 
} 

func (base *Base) Bar() { ... } 

type Foo struct { 
    Base 
    ... 
} 

func (foo *Foo) Bar() { 
    foo.Base.Bar() 
    ... 
} 
据我有限的知识，　匿名组合继承的方式是上面这种，　可是在web_c.go，　base_c.go中，类的名字完全一样，方法的声明也完全一样，且都属于www包，　从逻辑上讲，　如果我声明一个baseC类去调用GetPartnerId，　我该调用哪个呢(base_c.go 还是 web_c.go里的GetPartnerId)？

**Comment by atnet** [comment]
web_c.go 中调用GetPartnerId ，前提是web_c.go没有定义GetPartnerId。 
如果有的话，相当于重写了。执行的是web_c.go  里的实现。

这处代码是gof里web 筛选器的应用，这里有个示例代码：
https://github.com/atnet/gof/blob/master/web/demo/web_demo.go

**Comment by bzhkl** [comment]
谢谢　.
web_c.go 中调用GetPartnerId ，前提是web_c.go没有定义GetPartnerId。 
如果有的话，相当于重写了。执行的是web_c.go 里的实现。  

这个我明白, 但是　
type listC struct {
	*baseC
}
1,在list_c.go 中调用了GetPartner，　这GetPartner　是调用　web_c.go　还是　base_c.go中的？

2,如果list_c.go 中调用了baseC的GetPartner方法 ， 我怎么可以看出web_c.go 中的GetPartner重写了base_c.go中的GetPartner　， 而不是 base_c.go 中的GetPartner重写了web_c.go中的GetPartner？

**Comment by atnet** [comment]
我好像晕了，这我说不上来。这个在网上没有相关介绍的。
原则基本上是遵循OO的吧
